apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoincore.fullname" . }}
  labels:
    {{- include "bitcoincore.labels" . | nindent 4 }}
data:
  bitcoin.conf: |
    {{ .Values.chain }}=1

    {{ template "bitcoincore.check_semver" . }}
    {{- .Values.baseConfig | nindent 4 }}
    {{- .Values.config | nindent 4 }}
    {{- range .Values.connect }}
      {{- print "connect=" . | nindent 4}}
    {{- end }}