apiVersion: v1
kind: Pod
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
    app: {{ include "lnd.fullname" . }}
    {{- if .Values.collectLogs }}
    collect_logs: "true"
    {{- end }}
    chain: {{ .Values.global.chain }}
  annotations:
    kubectl.kubernetes.io/default-container: "lnd"
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  {{- if .Values.enableInitContainers }}
  initContainers:
    - name: prepare-files
      image: busybox
      command:
        - sh
        - -c
        - |
          # Read the hex-encoded macaroon from the ConfigMap
          HEX_MACAROON=$(cat /config/MACAROON_HEX)

          # Convert the hex-encoded macaroon to binary format
          echo "$HEX_MACAROON" | xxd -r -p > /shared-data/admin.macaroon

          # Ensure the file has the correct permissions
          chmod 644 /shared-data/admin.macaroon
      volumeMounts:
        - name: {{ .Values.sharedVolume.name }}
          mountPath: {{ .Values.sharedVolume.mountPath }}
        - name: config
          mountPath: /config
  {{- end }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: rpc
          containerPort: {{ .Values.RPCPort }}
          protocol: TCP
        - name: p2p
          containerPort: {{ .Values.P2PPort }}
          protocol: TCP
        - name: rest
          containerPort: {{ .Values.RestPort }}
          protocol: TCP
      livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 8 }}
      readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 8 }}
      startupProbe:
        {{- toYaml .Values.startupProbe | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      volumeMounts:
        - mountPath: {{ .Values.sharedVolume.mountPath }}
          name: {{ .Values.sharedVolume.name }}
        {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - mountPath: /root/.lnd/lnd.conf
          name: config
          subPath: lnd.conf
        - mountPath: /root/.lnd/tls.key
          name: config
          subPath: tls.key
        - mountPath: /root/.lnd/tls.cert
          name: config
          subPath: tls.cert
    {{- with .Values.extraContainers }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extraContainers }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  volumes:
    - name: {{ .Values.sharedVolume.name }}
      emptyDir: {}
    {{- with .Values.volumes }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    - configMap:
        name: {{ include "lnd.fullname" . }}
      name: config
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
