apiVersion: v1
kind: Pod
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
    app: {{ include "lnd.fullname" . }}
    {{- if .Values.collectLogs }}
    collect_logs: "true"
    {{- end }}
    chain: {{ .Values.global.chain }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  initContainers:
  - name: prepare-files
    image: busybox
    command:
      - sh
      - -c
      - |
        cp /root/.lnd/tls.cert /root/.lnd/tls_copy.cert
        chmod 644 /root/.lnd/tls_copy.cert
    volumeMounts:
      - name: lnd-data
        mountPath: /root/.lnd
      - name: config
        mountPath: /root/.lnd/tls.cert
        subPath: tls.cert
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: rpc
          containerPort: {{ .Values.RPCPort }}
          protocol: TCP
        - name: p2p
          containerPort: {{ .Values.P2PPort }}
          protocol: TCP
        - name: rest
          containerPort: {{ .Values.RestPort }}
          protocol: TCP
      livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 8 }}
      readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 8 }}
      startupProbe:
        {{- toYaml .Values.startupProbe | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      volumeMounts:
        - name: lnd-data
          mountPath: /root/.lnd
        {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - mountPath: /root/.lnd/lnd.conf
          name: config
          subPath: lnd.conf
        - mountPath: /root/.lnd/tls.key
          name: config
          subPath: tls.key
        - mountPath: /root/.lnd/tls.cert
          name: config
          subPath: tls.cert
    - name: circuitbreaker
      securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
      image: camillarhi/circuitbreaker:latest
      imagePullPolicy: IfNotPresent
      args:
          - "--network=regtest"
          - "--rpcserver=localhost:10009"
          - "--tlscertpath=/root/.lnd/tls_copy.cert"
          - "--macaroonpath=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
          - "--httplisten=0.0.0.0:9235"

      volumeMounts:
        - name: lnd-data
          mountPath: /root/.lnd
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - |
              # Check if tls.cert exists and is readable
              test -f /root/.lnd/tls.cert && echo "tls.cert found" || exit 1
              # Check if admin.macaroon exists and is readable
              test -f /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon && echo "macaroon found" || exit 1
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 1
  volumes:
    - name: lnd-data
      emptyDir: {}
    {{- with .Values.volumes }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    - configMap:
        name: {{ include "lnd.fullname" . }}
      name: config
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
