apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cln.fullname" . }}
  labels:
    {{- include "cln.labels" . | nindent 4 }}
data:
  config: |
    {{- .Values.baseConfig | nindent 4 }}
    {{- .Values.defaultConfig | nindent 4 }}
    {{- .Values.config | nindent 4 }}
    network={{ .Values.global.chain }}
    bind-addr=0.0.0.0:{{ .Values.P2PPort }}
    clnrest-port={{ .Values.RestPort }}
    bitcoin-rpcconnect={{ include "bitcoincore.fullname" . }}
    bitcoin-rpcport={{ index .Values.global .Values.global.chain "RPCPort" }}
    bitcoin-rpcpassword={{ .Values.global.rpcpassword }}
    alias={{ include "cln.fullname" . }}
    announce-addr=dns:{{ include "cln.fullname" . }}:9735
    database-upgrade=true
    bitcoin-retry-timeout=600
    clnrest-certs=/root/.lightning
  tls.cert: |
    -----BEGIN CERTIFICATE-----
    MIIB8TCCAZagAwIBAgIUJDsR6mmY+TaO9pCfjtotlbOkzJMwCgYIKoZIzj0EAwIw
    MjEfMB0GA1UECgwWbG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEPMA0GA1UEAwwGd2Fy
    bmV0MB4XDTI0MTExMTE2NTM1MFoXDTM0MTEwOTE2NTM1MFowMjEfMB0GA1UECgwW
    bG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEPMA0GA1UEAwwGd2FybmV0MFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEBVltIvaTlAQI/3FFatTqVflZuZdRJ0SmRMSJrFLP
    tp0fxE7hmteSt6gjQriy90fP8j9OJXBNAjt915kLY4zVvqOBiTCBhjAOBgNVHQ8B
    Af8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAd
    BgNVHQ4EFgQU5d8QMrwhLgTkDjWA+eXZGz+dybUwLwYDVR0RBCgwJoIJbG9jYWxo
    b3N0ggEqhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMCA0kAMEYC
    IQDPofN0fEl5gTwCYhk3nZbjMqJhZ8BsSJ6K8XRhxr7zbwIhAPsgQCFOqUWg632O
    NEO53OQ6CIqnpxSskjsFNH4ZBQOE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIIcFtWTLQv5JaRRxdkPKkO98OrvgeztbZ7h8Ev/4UbE4oAoGCCqGSM49
    AwEHoUQDQgAEBVltIvaTlAQI/3FFatTqVflZuZdRJ0SmRMSJrFLPtp0fxE7hmteS
    t6gjQriy90fP8j9OJXBNAjt915kLY4zVvg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cln.fullname" . }}-channels
  labels:
    channels: "true"
    {{- include "cln.labels" . | nindent 4 }}
data:
  source: {{ include "cln.fullname" . }}
  channels: |
    {{ .Values.channels | toJson }}
