name: test

on:
  pull_request:
  push:
    branches:
      - dev

jobs:

  ruff:
    # DISABLE FOR REWRITE
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v1
      - run: uv venv
      - run: uv pip install ruff
      - run: source .venv/bin/activate; ruff check .

  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v1
      - run: uv venv
      - run: uv pip install ruff
      - run: source .venv/bin/activate; ruff format .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test: [scenarios_test.py, rpc_test.py, graph_test.py, ln_test.py, dag_connection_test.py, logging_test.py]
        test: [scenarios_test.py, rpc_test.py, graph_test.py,               dag_connection_test.py, logging_test.py]
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v1
      - uses: azure/setup-helm@v4.2.0
      - uses: medyagh/setup-minikube@master
      - name: Run tests
        run: |
          echo Installing warnet python package for cli
          uv venv
          uv pip install -e .
        shell: bash
      - name: Run tests
        run: |
          source .venv/bin/activate
          ./test/${{matrix.test}}
